<?php

namespace TestBundle\Repository;

/**
 * TestIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestIndexRepository extends \Doctrine\ORM\EntityRepository
{
}
