<?php

namespace AppBundle\Repository;

/**
 * HelperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelperRepository extends \Doctrine\ORM\EntityRepository
{
}
