iw:
    path: /{_locale}
    defaults:  { _controller: IWBundle:IW:index, _locale: ru }
    requirements:
        _locale: '%app.locales%'

iw_routes:
    resource: '@IWBundle/Resources/config/routing.yml'
    prefix:   /{_locale}/iw
    requirements:
        _locale: '%app.locales%'

_security:
    resource: '@AuthenticationBundle/Resources/config/routing.yml'
    prefix:   /{_locale}/security
    requirements:
        _locale: '%app.locales%'