iw_user:
    resource: "@IWBundle/Resources/config/routing/user.yml"
    prefix:   /user

iw_play:
    resource: "@IWBundle/Resources/config/routing/play.yml"
    prefix:   /play

iw_helper:
    resource: "@IWBundle/Resources/config/routing/helper.yml"
    prefix:   /helper