iw_rpc:
    channel: sample/{method}
    handler:
        callback: 'iw.rpc' #related to the getName() or your RPC service
    requirements:
        method:
            pattern: "[a-z_]+" #accept all valid regex, don't put delimiters !