TestBundle\Entity\TestIndex:
    repositoryClass: TestBundle\Repository\TestIndexRepository
    type: entity
    table: test_index
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title_1:
            type: string
            length: 255
            nullable: true
            options:
                default: null
        title_2:
            type: string
            length: 255
            nullable: true
            options:
                default: 'Hi'
        description:
            type: text
            length: 2000
            nullable: true
            options:
                default: 'Hi'
        isActive:
            type: boolean
            name: is_active
            options:
                default: true
        deleted:
            type: boolean
            options:
                default: false
        created_at:
            type: datetime
            nullable: false
        updated_at:
            type: datetime
            nullable: false