testindex_index:
    path:     /{page}
    defaults: { _controller: "TestBundle:TestIndex:index", page: 1 }
    requirements:
        page: '\d+'
    methods:  GET

testindex_show:
    path:     /{id}/show
    defaults: { _controller: "TestBundle:TestIndex:show" }
    methods:  GET

testindex_new:
    path:     /new
    defaults: { _controller: "TestBundle:TestIndex:new" }
    methods:  [GET, POST]

testindex_edit:
    path:     /{id}/edit
    defaults: { _controller: "TestBundle:TestIndex:edit" }
    methods:  [GET, POST]

testindex_delete:
    path:     /{id}/delete
    defaults: { _controller: "TestBundle:TestIndex:delete" }
    methods:  DELETE
