_login:
    path: /login
    defaults:  { _controller: AuthenticationBundle:Authentication:index }

_logout:
    path: /logout

_registration:
    path: /registration
    defaults:  { _controller: AuthenticationBundle:Registration:index }